@hostname = localhost
@port = 3000
@baseurl = http://{{hostname}}:{{port}}
@contentType = application/json

### 

@name = Foo
@email = foo@mail.com
@password = 123foo
@passwordConfirmation = 123foo

POST {{baseurl}}/api/signup
Content-Type: {{contentType}}

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "passwordConfirmation": "{{passwordConfirmation}}"
}