import crypto from 'crypto'
import { UUIDGeneratorAdapter } from './uuid-generator-adapter'

jest.mock('crypto', () => ({
  randomUUID(): string {
    return 'unique_id'
  }
}))

const makeSut = () => new UUIDGeneratorAdapter()

describe('UUID Generator Adapter', () => {
  const sut = makeSut()

  it('Should return a UUID string on success', () => {
    const uuid = sut.generate()
    expect(uuid).toBe('unique_id')
  })

  it('Should not throw if crypto module throws', () => {
    jest.spyOn(crypto, 'randomUUID').mockImplementationOnce(() => {
      throw new Error()
    })
    const uuid = sut.generate()
    expect(uuid).toBeDefined()
  })

  it('Should return a numeric id string generated by combination of Date.now() and Math.random() if crypto module throws', () => {
    jest.spyOn(crypto, 'randomUUID').mockImplementationOnce(() => {
      throw new Error()
    })
    const uuid = sut.generate()
    expect(uuid).toBeDefined()
    expect(uuid.length).toBeTruthy()
    expect(typeof +uuid).toBe('number')
  })
})
